name: spandx
sources:
  bundler: true
cache_path: '.github/licensed'
allowed:
  - apache-2.0
  - bsd-2-clause
  - mit
reviewed:
  bundler:
    - sorted_set
bundler:
  without:
    - development
    - test
