require:
  - rubocop-rspec

AllCops:
  Exclude:
    - 'pkg/**/*'
    - 'spec/fixtures/**/*'
    - 'vendor/bundle/**/*'
  TargetRubyVersion: 2.5

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ParameterAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Metrics/MethodLength:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'Rakefile'
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Layout/LineLength:
  Exclude:
    - 'spec/**/*.rb'
  IgnoredPatterns:
    - '^#*'

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: 'single_quotes'

Style/WordArray:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

RSpec/ExampleLength:
  Max: 80

RSpec/NamedSubject:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'
