---
name: timers
version: 4.3.0
type: bundler
summary: Pure Ruby one-shot and periodic timers
homepage: https://github.com/socketry/timers
license: mit
licenses:
- sources: README.md
  text: "Released under the MIT license.\n\nCopyright, 2018, by [Samuel G. D. Williams](http://www.codeotaku.com/samuel-williams).
    \ \nCopyright, 2016, by [Tony Arcieri](bascule@gmail.com).  \nCopyright, 2016,
    by Jeremy Hinegardner.  \nCopyright, 2016, by Sean Gregory.  \nCopyright, 2016,
    by Chuck Remes.  \nCopyright, 2016, by Utenmiki.  \nCopyright, 2016, by Ron Evans.
    \ \nCopyright, 2016, by Larry Lv.  \nCopyright, 2016, by Bruno Enten.  \nCopyright,
    2016, by Jesse Cooke.  \nCopyright, 2016, by Nicholas Evans.  \nCopyright, 2016,
    by Dimitrij Denissenko.  \nCopyright, 2016, by Ryan LeCompte.  \n\nPermission
    is hereby granted, free of charge, to any person obtaining a copy\nof this software
    and associated documentation files (the \"Software\"), to deal\nin the Software
    without restriction, including without limitation the rights\nto use, copy, modify,
    merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and
    to permit persons to whom the Software is\nfurnished to do so, subject to the
    following conditions:\n\nThe above copyright notice and this permission notice
    shall be included in\nall copies or substantial portions of the Software.\n\nTHE
    SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED,
    INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A
    PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\nAUTHORS OR COPYRIGHT
    HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\nLIABILITY, WHETHER IN AN ACTION
    OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\nOUT OF OR IN CONNECTION WITH THE
    SOFTWARE OR THE USE OR OTHER DEALINGS IN\nTHE SOFTWARE."
notices: []
