name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.5', '2.6', '2.7' ]
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: recursive
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: setup
        run: ./bin/setup
      - name: integration
        run: ./bin/test spec/integration
      - name: unit
        run: ./bin/test spec/unit
      - name: lint
        run: ./bin/lint
