name: omnibus
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: recursive
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: setup
        run: ./bin/setup
      - name: build
        run: bundle exec omnibus build spandx
